name: makassar-ml
channels:
  - conda-forge
dependencies:
  - conda-build
  - ipykernel
  - jupyter
  - keras-tuner
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pytest
  - pyyaml
  - scikit-learn
  - seaborn
  - tensorflow
  - tensorflow-datasets
  - tqdm
