name: makassar-ml
channels:
  - conda-forge
  - pytorch
dependencies:
  - pytest
  - pytorch-lightning
  - ipykernel
  - tqdm
  - matplotlib
  - pandas
  - requests
  - pytorch
  - torchvision
  - conda-build
  - notebook
