[project]
name = "makassar-ml"
version = "0.1.0"
description = ""
authors = [
    {name = "Alexander DeRieux", email = "alexander.derieux@gmail.com"},
]
dependencies = [
    "torch>=1.10.1",
    "numpy>=1.22.1",
    "pandas>=1.3.5",
    "matplotlib>=3.5.1",
    "torchvision>=0.11.2",
    "tqdm>=4.62.3",
    "requests>=2.27.1",
    "pytorch-lightning>=1.5.9",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[project.urls]
homepage = ""

[project.optional-dependencies]
[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "ipykernel>=6.7.0",
    "jupyterthemes>=0.20.0",
    "pytest>=6.2.5",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
