# Dataset.
dataset:
  name: beijingpm25
  parameters:
    path: ${HOME}/research/makassar/datasets/beijing_pm25
    in_feat: &ID_in_feat ['TEMP','PRES','Iws','Is','Ir']
    out_feat: &ID_out_feat ['DEWP']
    in_seq_len: &ID_in_seq_len 24 # Alias for future use.
    out_seq_len: &ID_out_seq_len 1 # Alias for future use.
    shift: 1
    split: [0.7,0.2,0.1]
    shuffle: False

# Model definition.
model:
  name: transformer_time2vec_encoder_pool_fc
  parameters:
    in_seq_len: *ID_in_seq_len
    in_feat: 5
    out_feat: 1
    fc_units: [64,64]
    embed_dim: 64
    n_heads: 8
    ff_dim: 256
    dropout: 0.1
    n_encoders: 3

# Training configuration.
train:
  batch_size: 128
  epochs: 10

  # Optimizer.
  optimizer:
    name: adam
    parameters:
      lr: 0.001

  # Compile parameters.
  compile:
    loss: mse
    metrics: ['mae','mape']

# Root directory paths.
roots:
  checkpoint_root: $HOME/research/makassar/checkpoints
  image_root: ${HOME}/research/makassar/images
  table_root: ${HOME}/research/makassar/tables
  hp_tuning_root: ${HOME}/research/makassar/hp_tuning
  keras_tuner_path: ${HOME}/research/makassar/keras_tuner