# Dataset.
dataset:
  name: fused_plant_village_beijingpm25_classification
  parameters:
    timeseries_path: ${HOME}/research/makassar/datasets/beijing_pm25
    timeseries_datetime_column: 'datetime'
    timeseries_features_in: &ID_timeseries_features_in ['TEMP','DEWP','PRES','Iws']
    timeseries_seq_len_in: &ID_seq_len_in 24
    timeseries_reserve_offset_index: *ID_seq_len_in # length of timedelta
    image_shape: &ID_image_shape [72,72,3]
    split: [0.7,0.2,0.1]
    shuffle_files: False

# Model definition.
model:
  name: FuT_image_timeseries_classifier
  parameters:
    image_shape: *ID_image_shape
    seq_shape: [*ID_seq_len_in, !len [*ID_timeseries_features_in]] # (seq,feat)
    n_class: 38
    patch_size: 6
    image_embed_dim: 
      values:
        - 16
        - 32
    seq_embed_dim:
      values:
        - 5
        - 10
    n_heads: 
      values:
        - 8
    ff_dim:
      values:
        - 256
    dropout:
      values:
        - 0.1
        - 0.3
    n_encoders:
      values:
        - 3
        - 6
    fc_units: []

# Training configuration.
train:
  batch_size: 256
  epochs: 30

  # Optimizer.
  optimizer:
    name: adam
    parameters:
      lr:
        values:
          - 1.0e-3
          - CosineDecay:
              initial_learning_rate: 1.0e-3
              decay_steps: 4470
              alpha: 0.1
          - CosineDecayRestarts:
              initial_learning_rate: 1.0e-3
              first_decay_steps: 1490 # 4470/3
              alpha: 0.1
              m_mul: 0.8

  # Compile parameters.
  compile:
    loss: sparse_categorical_crossentropy
    metrics: ['accuracy']

# LaTeX table parameters.
latex_table_results:
  environment: "longtable"
  caption: "Tuned \\ac{fut} single-head classifier performance on fusion dataset. Rows are sorted by column $val\\_loss$ in ascending order to highlight best-performing models. Best performance values for each column are highlighted in \\textbf{bold}."
  position: "hbt"
  sort_values:
    by: 'val_loss'
    ascending: True
latex_table_parameters:
  environment: "longtable"
  caption: "Tuned \\ac{fut} single-head classifier model parameters. Rows are sorted by column $model$ in ascending order."
  position: "hbt"
  header: [model, dropout, ff_dim, image_embed_dim, lr, n_encoders, n_heads, patch_size, seq_embed_dim]
  sort_values:
    by: 'model'
    ascending: True

# Plotting.
highlight_plot:
  models: [43, 42, 17]

# Root directory paths.
roots:
  project_root: &ID_project_root ${HOME}/research/makassar/
  checkpoint_root: !join [*ID_project_root, checkpoints]
  image_root: !join [*ID_project_root, images]
  table_root: !join [*ID_project_root, tables]
  hp_tuning_root: !join [*ID_project_root, hp_tuning]
  keras_tuner_path: !join [*ID_project_root, keras_tuner]